'use strict';

const fs = require('fs');

const COMMENT_MARKER = '<!-- security-health-check -->';
const SEVERITY_EMOJI = { critical: '🔴', high: '🟠', medium: '🟡', low: '🔵' };

function scoreEmoji(score) {
  if (score >= 90) return '🟢';
  if (score >= 70) return '🟡';
  return '🔴';
}

function formatComment(report) {
  const { score, threshold, passed, filesScanned, categories } = report;
  const statusEmoji = passed ? '✅' : '❌';
  const barFilled = Math.round(score / 5);
  const bar = '█'.repeat(barFilled) + '░'.repeat(20 - barFilled);

  let body = `${COMMENT_MARKER}\n`;
  body += `## 🔒 Security Health Check\n\n`;
  body += `**Score: ${score}/100** ${statusEmoji} ${passed ? 'PASS' : 'FAIL'} (threshold: ${threshold})\n\n`;
  body += `\`${bar}\`  ${filesScanned} files scanned\n\n`;

  body += `| Category | Score | Weight | Findings |\n`;
  body += `|----------|-------|--------|----------|\n`;
  for (const cat of categories) {
    const catIcon = scoreEmoji(cat.score);
    body += `| ${catIcon} ${cat.category} | ${Math.round(cat.score)}/100 | ${Math.round(cat.weight * 100)}% | ${cat.findings.length} |\n`;
  }
  body += '\n';

  const allFindings = categories.flatMap(c =>
    c.findings.map(f => ({ ...f, category: c.category }))
  );

  if (allFindings.length > 0) {
    body += `<details>\n<summary>🔍 Findings (${allFindings.length} issue${allFindings.length !== 1 ? 's' : ''})</summary>\n\n`;

    const byFile = {};
    for (const f of allFindings) {
      const key = f.file || 'project-level';
      if (!byFile[key]) byFile[key] = [];
      byFile[key].push(f);
    }

    for (const [file, findings] of Object.entries(byFile)) {
      body += `**\`${file}\`**\n\n`;
      for (const f of findings) {
        const icon = SEVERITY_EMOJI[f.severity] || '⚪';
        const line = f.line ? ` (line ${f.line})` : '';
        body += `- ${icon} **[${f.severity}]** ${f.message}${line} *(-${f.deduction}pts)*\n`;
      }
      body += '\n';
    }

    body += '</details>\n\n';
  }

  const allGood = categories.flatMap(c => c.goodPractices);
  if (allGood.length > 0) {
    body += `<details>\n<summary>✅ Good Practices (${allGood.length})</summary>\n\n`;
    for (const g of allGood) {
      body += `- ✓ ${g}\n`;
    }
    body += '\n</details>\n\n';
  }

  body += `---\n*Generated by [security-health-check](https://github.com/marketplace/actions/security-health-check)*`;

  return body;
}

module.exports = async function ({ github, context, core }) {
  const reportPath = '/tmp/security-report.json';

  let report;
  try {
    report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
  } catch (e) {
    core.setFailed(`Failed to read security report: ${e.message}`);
    return;
  }

  const { score, categories } = report;
  const hasFindings = categories.some(c => c.findings.length > 0);

  core.setOutput('score', String(score));
  core.setOutput('has_findings', String(hasFindings));

  const postComment = process.env.POST_COMMENT !== 'false';
  if (!postComment || !context.payload.pull_request) return;

  const body = formatComment(report);
  const { owner, repo } = context.repo;
  const issue_number = context.payload.pull_request.number;

  const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number });
  const existing = comments.find(c => c.body.includes(COMMENT_MARKER));

  if (existing) {
    await github.rest.issues.updateComment({ owner, repo, comment_id: existing.id, body });
  } else {
    await github.rest.issues.createComment({ owner, repo, issue_number, body });
  }
};
